[config]
schemaVersion = "0.0.1"

[package]
namespace = "zannc"
name = "Godly_Boon_Return"
versionNumber = "2.0.0"
description = ""
websiteUrl = "https://github.com/excellent-ae/zannc-Practical_Gods"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.70"
SGG_Modding-ModUtil = "4.0.1"
LuaENVY-ENVY = "1.2.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"
SGG_Modding-SJSON = "1.0.0"
zannc-Droppable_Gods = "1.0.1"
zannc-GodsAPI = "1.0.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"

[[build.copy]]
source = "./lovely"
target = "./lovely"

[[build.copy]]
source = "./packages"
target = "./plugins_data"

[publish]
repository = "https://thunderstore.io"
communities = ["hades-ii"]

[publish.categories]
hades-ii = ["mods"]
